Add typescript declaration file
KhalisFoundation/anvaad-js pull request #85
Opened 2020-06-03 16:48 UTC by AkalUstat

2020-06-03 16:59 UTC, AkalUstat commented
Tested on MyPothi local code and declaration files worked

2020-06-04 01:46 UTC, AkalUstat commented
@irvanjitsingh @tsingh777

2020-06-04 07:10 UTC, tsingh777 requested changes

2020-06-04 07:10 UTC, tsingh777 commented on package.json
> +  "types": "src/index.d.ts",
shouldn't this be `dist/index.d.ts` 

would either need the build command to copy it to the dist folder or have webpack include it some how (the former would be easier). 
change the build in scripts to. 
```"build": "webpack -p && mv src/index.d.ts dist/index.d.ts", ```

so when ci/cd does `npm publish`, it will include it.

2020-06-04 07:10 UTC, tsingh777 commented on src/index.d.ts
> +export const alphabetize: (sentenceArray: string[], type: 'english' | 'unicode') =>  string;
type can be optional since we default to english. https://github.com/KhalisFoundation/anvaad-js/blob/master/src/alphabetize.js#L100

```
type?: 'english' | 'unicode'
```

2020-06-04 07:10 UTC, tsingh777 commented on src/index.d.ts
> +export const  ascii: (letters: string) => string ;
letters is technically also optional but spits back and empty string. https://github.com/KhalisFoundation/anvaad-js/blob/master/src/ascii.js#L18

Not sure how valuable of a use case that is to someone could make optional here too.
```
letters?: string
```

personally I'm fine with someone using anvaad with typescript being forced to pass a param.

2020-06-04 07:10 UTC, tsingh777 commented on src/index.d.ts
> +export const translit: (gurmukhi: string) =>  string;
also takes language and map https://github.com/KhalisFoundation/anvaad-js/blob/master/src/translit.js#L22
```
export const translit: (gurmukhi: string, language?: 'english' | 'devnagri', 'ipa', 'shahmukhi', map?: null | Map<string, string> ) =>  string;
```

2020-06-04 07:10 UTC, tsingh777 commented on src/index.d.ts
> +export const unicode: (text: string, reverse?: boolean, simplify?: boolean) => string;
text is defaulted too https://github.com/KhalisFoundation/anvaad-js/blob/master/src/unicode.js#L373

This is fine though. No use case I can see where a typescript user would call this function with no params.

2020-06-04 07:20 UTC, tsingh777 commented on package.json
> +    "@types/node": "^14.0.9",
this shouldn't be needed.

2020-07-08 21:57 UTC, AkalUstat commented
bump @irvanjitsingh

2020-07-09 00:55 UTC, tsingh777 commented on package.json
> +  "types": "src/index.d.ts",
@AkalUstat this line still needs to be updated.

2020-07-09 02:08 UTC, AkalUstat commented on package.json
> +  "types": "src/index.d.ts",
fixed

2020-07-09 02:30 UTC, tsingh777 approved these changes

2020-07-09 19:36 UTC, merged